Post.delete_all
print "Seeding database with posts..."

# Create Lorem texts for seeds
content1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pretium convallis faucibus. Pellentesque eu erat ipsum. Donec at risus sit amet felis ultrices pretium in posuere ligula. Duis at auctor augue, et faucibus risus. Vestibulum at dignissim velit. Donec ac velit venenatis, hendrerit tellus vestibulum, maximus arcu. Mauris at laoreet massa, et mollis mauris. Pellentesque vel ipsum odio. Nulla eu blandit ipsum. Donec quis feugiat enim. Donec at purus magna. Etiam gravida leo non eleifend posuere. Nunc a vulputate lacus. In interdum mollis metus, et consequat est ullamcorper eu. Etiam et faucibus orci.

  Aliquam fermentum nec lacus eget consequat. Suspendisse vitae justo sodales, blandit massa id, maximus nulla. Nulla nec purus in est rutrum venenatis vitae ac turpis. Fusce vehicula tortor est, et imperdiet nulla sagittis at. Donec ac dui nec diam semper posuere. Nam lectus arcu, blandit et pharetra sit amet, varius ut sapien. Phasellus vitae dignissim diam, quis vulputate lacus.

  Curabitur efficitur consequat ante non vulputate. Integer efficitur, ex ac pretium volutpat, enim ligula bibendum nulla, venenatis pharetra est ipsum et massa. Ut vitae mi blandit, accumsan quam tincidunt, dapibus ligula. Phasellus dolor magna, varius vel aliquam nec, facilisis sit amet ipsum. Integer vulputate elit tortor, sed pellentesque mi molestie eu. Mauris non nulla sodales, hendrerit diam quis, hendrerit risus. Etiam non lacus quis orci gravida faucibus suscipit eget dui. In varius faucibus sem, in ullamcorper justo mollis a. Aliquam sed ante massa. Curabitur mi risus, pulvinar in ultricies a, dictum eget neque. Nullam eget tristique purus.

  Vivamus tincidunt iaculis accumsan. Curabitur feugiat turpis a arcu aliquam malesuada. Suspendisse tempor risus in augue dapibus, vitae pulvinar purus viverra. Nulla in ultrices leo. Suspendisse quis ex erat. In tincidunt enim justo, nec pellentesque ligula rhoncus ut. Nam massa urna, malesuada sit amet sollicitudin nec, egestas et metus. Aenean vestibulum dolor id pellentesque laoreet. Suspendisse mi massa, eleifend nec laoreet quis, tempor sit amet urna. Nulla lobortis nec lectus in venenatis. Quisque maximus ullamcorper nisi. Nulla sem metus, suscipit at faucibus consectetur, placerat laoreet nunc. Ut vitae felis sapien. Praesent eu tempor ipsum. Cras varius lorem at ligula lacinia, id ullamcorper felis condimentum.

  Nullam varius nulla facilisis, condimentum diam sit amet, feugiat arcu. Donec viverra tincidunt nisi ac viverra. Aliquam malesuada dapibus quam a vestibulum. Sed id aliquet enim, vitae suscipit magna. Aenean viverra id metus eu dapibus. Aliquam ac turpis sed mi cursus sagittis sit amet sit amet elit. Morbi a enim efficitur, aliquam mi id, maximus mi. Phasellus pellentesque tincidunt consequat. Mauris ut nulla molestie, mollis risus ut, vulputate dui. Sed libero velit, varius sit amet lorem et, dictum cursus augue. Aenean at sem semper, dictum arcu pretium, fringilla mi. Morbi a viverra ex, at auctor sem. Nulla ut leo pulvinar, venenatis eros non, convallis sapien. Phasellus non mauris commodo, blandit diam ac, fringilla nisi. Mauris gravida dui dolor, ut lobortis eros ultrices eget.

  Ut vel consequat urna. Etiam eu consequat enim. Suspendisse pharetra risus erat, sit amet rutrum augue finibus at. Sed vel convallis mi. Quisque sed aliquam justo, vel euismod enim. Cras luctus mauris ac semper accumsan. Aliquam nec ligula porttitor, convallis leo vel, bibendum ligula. Etiam laoreet elit eu libero pharetra convallis. Ut in turpis sit amet lorem lobortis ornare. Sed cursus et lectus vel vestibulum. Aliquam erat volutpat. Phasellus ornare ex magna, non volutpat arcu tincidunt finibus.

  Nulla sit amet purus neque. Fusce facilisis luctus libero eget elementum. Curabitur ac ante et lectus elementum lacinia. Proin ultrices finibus mauris at semper. Fusce sapien risus, ullamcorper nec sollicitudin ut, fermentum at orci. Fusce lacinia risus id ultrices aliquet. Vivamus nisl urna, vestibulum nec felis a, varius scelerisque risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque condimentum lobortis urna ut vehicula. Nam et pulvinar ante. Quisque consequat lorem sed elit aliquam, a imperdiet est aliquam.

  Suspendisse ac est eget orci vulputate iaculis et vel nisl. Vestibulum mattis tristique lacus eu cursus. Ut at volutpat justo, in facilisis diam. Sed eget commodo metus, eu blandit quam. Proin eget augue aliquam, mollis massa commodo, convallis urna. Suspendisse at nibh facilisis diam mollis feugiat sed nec est. Aenean non facilisis odio. Duis egestas at leo dictum eleifend. Maecenas lobortis augue mauris, sed sagittis enim fermentum sit amet. Quisque ultrices vel metus eget facilisis. Sed rutrum augue id tincidunt aliquam.

  Duis felis turpis, cursus a pharetra quis, dictum eget tortor. Morbi iaculis semper viverra. Nulla maximus faucibus tincidunt. Phasellus non luctus ipsum, ac pellentesque elit. In iaculis molestie dui, ac finibus ligula dignissim quis. Quisque vulputate dolor ut sapien accumsan, et auctor nisl egestas. Suspendisse convallis vitae nibh a bibendum. Maecenas ultricies, nisl pretium pulvinar bibendum, orci elit lobortis nulla, ac imperdiet turpis nisi ac quam. Cras scelerisque ligula ac massa rutrum, at dictum enim tempus. Cras sed finibus neque. Morbi vitae quam nisi. Sed eget interdum libero. Proin cursus, neque eu pellentesque euismod, mi sem pharetra leo, at hendrerit lectus nibh vitae nibh.

  Etiam lobortis dapibus lectus sit amet vulputate. Cras pretium elementum nulla, sed porta erat tristique sit amet. Vestibulum pulvinar lectus eget iaculis scelerisque. Cras ornare nibh sed sollicitudin egestas. Curabitur in finibus quam, et facilisis urna. In nisi dolor, pulvinar nec dignissim a, faucibus a nisl. Donec tincidunt leo ac mi feugiat iaculis ac sed dolor. Nulla neque nibh, vulputate sed arcu non, pretium rhoncus nisl. Ut tempor lacus eu vulputate vulputate. Nulla cursus vulputate diam, a condimentum eros ullamcorper et. Suspendisse pharetra quis arcu sed consequat. "

content2 = "Ut ut mi sit amet velit tincidunt rhoncus vel et purus. Sed mollis sodales aliquet. In scelerisque risus purus, quis blandit justo cursus a. Aliquam eget tellus neque. Donec faucibus velit vel diam lobortis, vitae scelerisque metus condimentum. Fusce sed ante magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sed turpis ut libero efficitur eleifend ac nec nulla. Phasellus aliquet felis vel mauris imperdiet molestie.

  Proin pretium tincidunt erat ac euismod. Phasellus aliquet lacus mi, et ullamcorper risus lacinia ut. Quisque interdum, arcu a dignissim finibus, massa metus mollis ipsum, a finibus dui diam at diam. Integer tempus tortor id felis aliquet commodo. Praesent luctus hendrerit nibh, ac maximus nunc dignissim quis. Sed nunc nisl, feugiat eu magna id, commodo molestie leo. Sed non enim sit amet nibh interdum mattis. Maecenas ut libero augue. Quisque sed tincidunt ante, ac iaculis eros. Mauris quam nibh, hendrerit quis dapibus non, bibendum eu urna.

  In vulputate erat quis nibh maximus consequat. In at consequat urna. In congue ipsum sed purus porttitor vehicula. Quisque vitae placerat erat, fringilla ullamcorper erat. In cursus ligula quis mauris malesuada ultricies. Sed condimentum ligula fringilla purus malesuada auctor. Proin eu erat eget enim porta pharetra nec eget ex. Donec faucibus diam est, vel faucibus ipsum lacinia quis. Suspendisse dictum viverra est et vestibulum. In tempor mattis euismod.

  Nam vitae leo non orci mattis semper. Sed scelerisque quam mauris, id posuere enim ornare ac. Vivamus lobortis suscipit mauris, nec finibus diam iaculis id. Donec tempor, ligula non semper laoreet, elit lorem finibus quam, vitae tincidunt mi dolor et sapien. Sed rutrum enim sed odio aliquet hendrerit. Nunc quis volutpat tellus, ac tristique metus. Mauris condimentum turpis vitae arcu mollis placerat. Integer eu mauris mattis, tristique nisl ut, maximus arcu. Quisque facilisis diam id justo aliquet pellentesque sit amet eu sapien. Etiam a erat at ante pharetra sagittis. Sed rutrum dui feugiat ultrices placerat. Curabitur gravida est sed nulla malesuada, id eleifend metus iaculis. Vivamus lacinia felis vel consectetur condimentum. Nunc vel viverra erat. Quisque euismod nisl risus.

  Nam vel suscipit justo. Donec id placerat elit. Pellentesque ut hendrerit erat, id condimentum quam. Nunc lorem est, tincidunt a commodo id, interdum ut elit. Aenean ut bibendum enim. Pellentesque eget interdum justo, vel ultrices diam. Aenean non dignissim nulla. Etiam eleifend est eu lectus ullamcorper porta. Proin ac tempus justo. In euismod volutpat dolor, vel semper augue vulputate sit amet. Duis facilisis turpis sed sem commodo vulputate. Maecenas quam mi, suscipit non commodo et, commodo ac neque. Sed rhoncus sapien in venenatis lacinia. Suspendisse porta facilisis mattis. Nulla enim eros, iaculis eget bibendum in, dapibus dictum magna.

  Proin tempor ut nisl quis cursus. Curabitur blandit luctus lacinia. Etiam luctus suscipit nisl, at gravida arcu vehicula scelerisque. Suspendisse eget risus eu augue pretium vehicula. In pharetra at ligula et porttitor. Suspendisse posuere quam turpis, at varius sapien aliquam in. Aenean ut tempor orci. Nunc non posuere quam, quis iaculis lorem. Maecenas vitae lacus nec ex tristique dictum eu et arcu. Etiam vestibulum, mi vel ultricies condimentum, ipsum erat ultricies eros, at vulputate ante nunc vitae enim. Vestibulum vulputate tempus tempus. Sed in lacinia augue. Praesent elementum magna hendrerit metus rhoncus, at placerat risus bibendum.

  Duis tempor semper mi ut tincidunt. Nulla pellentesque nibh gravida ex venenatis, ac placerat nisi rutrum. Ut nec erat at eros malesuada consectetur eu eu magna. In elementum dui lectus, vitae lobortis sapien congue sed. Etiam quis nibh diam. Aliquam sit amet cursus augue. Vestibulum suscipit ut nibh quis molestie. Aliquam erat volutpat. Vestibulum gravida aliquam mi, quis volutpat mauris pretium tincidunt. Cras a orci dui. Aenean euismod lorem sit amet urna mattis, non pharetra nunc dictum.

  Mauris in massa mollis, dignissim ipsum in, porttitor dolor. Pellentesque id leo a metus suscipit faucibus eget id nisi. Pellentesque volutpat tincidunt pellentesque. Nam ut commodo elit. Vivamus venenatis ac odio eu tincidunt. Pellentesque interdum, dui elementum molestie commodo, neque dui tincidunt quam, vel cursus felis lacus quis felis. Integer elementum metus quis ex interdum venenatis. Morbi vulputate fringilla quam, venenatis convallis mi pretium porta. Maecenas sollicitudin non nisi quis eleifend. Aliquam vel lacinia risus.

  Cras consectetur lacinia sem at tincidunt. Proin sit amet lorem sit amet nibh euismod aliquam. Maecenas id sollicitudin neque. Cras lobortis enim vitae lectus auctor euismod. Pellentesque in lectus risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dapibus nisl sit amet nisi feugiat rhoncus. Ut at feugiat enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut volutpat nulla eget velit malesuada mollis. Morbi ut egestas mauris. Morbi sed est ac metus volutpat congue. Aliquam sapien tellus, fermentum non feugiat non, vehicula eu enim. Quisque ultrices scelerisque nulla in dignissim. Suspendisse mattis felis ut dictum eleifend.

  Vivamus a ornare massa. Integer rutrum, tellus ut porta blandit, lacus risus euismod mauris, at egestas quam turpis ac risus. Maecenas et neque non nunc volutpat faucibus. Pellentesque faucibus urna justo, a fringilla augue rhoncus a. Integer volutpat est convallis nisl egestas, sagittis convallis nisl euismod. Aliquam maximus iaculis purus volutpat vestibulum. Aliquam dapibus nisl eget tortor vulputate interdum. 855 words"

content3 = "Praesent tortor est, semper ut imperdiet et, cursus venenatis felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tincidunt ultricies velit, eu vestibulum justo consectetur nec. Nam diam lorem, aliquam sit amet odio quis, euismod euismod massa. Pellentesque in lacus turpis. Aliquam a suscipit ante, eu pharetra neque. Etiam elementum enim ac sapien euismod, ac mollis nibh lobortis. Phasellus non tellus molestie ex viverra maximus et sed massa. Morbi nibh diam, accumsan vitae libero vel, commodo finibus neque.

  Cras vitae quam tempor risus lacinia elementum a at mauris. Nullam pellentesque vel massa vitae commodo. Ut dignissim purus quis libero facilisis, id convallis turpis tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc nec auctor nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus pharetra id tellus vel dignissim. Maecenas fermentum condimentum dolor eget lobortis.

  Quisque aliquet feugiat neque. Nulla at porta orci. Morbi gravida dictum imperdiet. Proin eu ipsum lobortis, euismod lectus dignissim, varius elit. Curabitur sit amet aliquet leo, ultricies vestibulum lorem. Quisque a facilisis felis. Sed hendrerit nunc enim, sit amet consequat ligula laoreet nec.

  Nullam placerat lobortis nisi quis laoreet. Donec luctus malesuada ex sed sodales. Duis cursus eleifend venenatis. In hac habitasse platea dictumst. Morbi eleifend, risus non fermentum rhoncus, sem massa tincidunt felis, a sagittis risus diam vitae lectus. Pellentesque velit mi, interdum sed diam id, accumsan tristique leo. Ut scelerisque metus tellus, dictum tempus lorem porttitor id. Nullam consectetur nunc a dui egestas lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi vulputate est ac mauris ullamcorper pellentesque in a leo. Donec malesuada pellentesque mi non volutpat. Ut molestie maximus convallis.

  Quisque ornare iaculis nisl, sodales vehicula magna sollicitudin vitae. Proin vestibulum vitae nibh eget consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus pretium nulla nec ornare viverra. Nulla ipsum felis, rhoncus nec vehicula ut, elementum sit amet nisl. Nullam dapibus sit amet augue ut consequat. Donec congue bibendum blandit. In quis sapien pretium, convallis erat vel, maximus metus. Phasellus est nulla, consequat et eleifend quis, fringilla sit amet sapien. Aliquam volutpat accumsan iaculis. Aliquam nunc diam, tincidunt et lobortis sit amet, interdum ut tellus. Nullam feugiat lacinia sapien, maximus mollis urna dictum pharetra. Cras feugiat risus sit amet velit molestie suscipit.

  Nunc et commodo est, non ultrices ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec convallis diam risus, vel mollis elit varius vitae. Vestibulum eu sollicitudin magna. Vivamus dictum convallis risus, quis posuere dui facilisis nec. Pellentesque id lacus tortor. Aliquam eleifend leo vitae arcu vehicula, id consectetur metus condimentum. Aliquam aliquet sodales accumsan. Vivamus imperdiet tellus metus, non viverra augue auctor et.

  Curabitur at aliquet orci, a mattis massa. Fusce varius urna ut ornare pellentesque. Donec elementum felis vel tincidunt venenatis. Pellentesque imperdiet ex sed pellentesque commodo. Phasellus nibh lacus, rhoncus sit amet fermentum vel, sagittis non leo. Duis egestas rutrum orci. Proin et blandit diam. Aenean gravida dignissim sapien nec mollis.

  Mauris scelerisque eros a diam lacinia, at dictum lorem tempus. Phasellus vulputate dapibus rutrum. Donec sodales bibendum gravida. Nullam posuere faucibus gravida. Maecenas elit enim, egestas eget est id, consectetur porta diam. Etiam vitae metus pharetra nunc bibendum mollis. Aliquam in justo ultrices, dictum risus in, finibus velit. Phasellus lacinia libero sed facilisis venenatis. Morbi accumsan quam vel nisl rhoncus tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Nullam interdum dapibus lacus, nec blandit dui pretium non. Pellentesque nec risus elit. Donec placerat, urna eget elementum accumsan, erat lorem condimentum ex, eget porta ex elit sit amet libero. Quisque eget vestibulum erat. Duis hendrerit elit ex, ut luctus nulla pharetra ac.

  Proin in turpis in enim faucibus accumsan vel sed diam. Nam dictum, elit eget posuere imperdiet, turpis sem ultricies enim, et facilisis quam ex vel augue. Nunc finibus, quam eget condimentum venenatis, tortor tortor lobortis justo, sed bibendum est mauris at lectus. Quisque tempor a ante a ultricies. Praesent quis volutpat quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec id sollicitudin nisl, vel gravida metus. In hac habitasse platea dictumst. Aliquam sit amet commodo est, eget venenatis orci.

  Cras molestie lacus id nisl imperdiet porttitor. Suspendisse consectetur condimentum euismod. Pellentesque tincidunt eros in justo aliquet, et rutrum enim auctor. Integer mauris felis, efficitur ut rutrum at, rutrum a sapien. Aenean finibus elit ut lacus sodales, vitae sodales ex dignissim. Mauris non nibh sit amet elit facilisis gravida non ac purus. Nulla volutpat velit nec varius hendrerit. Maecenas a nisi a lorem condimentum sollicitudin in nec urna. Maecenas tristique nunc ut vehicula varius. Donec fringilla orci ipsum, ut dignissim nunc gravida ut. 805 words"

content4 = "Cras pulvinar libero sit amet tortor semper, vitae semper ligula egestas. In cursus enim nec odio efficitur ultricies. Donec consequat et tellus at semper. Pellentesque nec felis non arcu interdum faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec volutpat augue at magna pulvinar scelerisque. Donec sagittis arcu eget ultricies tincidunt. Nunc euismod consequat neque. Etiam ligula nunc, eleifend nec felis tempor, vestibulum ullamcorper ipsum.

  Nulla suscipit, est quis feugiat scelerisque, magna odio gravida sapien, eget mollis velit nisi vel felis. Suspendisse potenti. Integer vel neque erat. Donec sed neque fringilla, ultrices purus vitae, tincidunt dui. Suspendisse sit amet massa a odio aliquam elementum. Etiam cursus enim id justo consectetur, sed finibus nulla porta. Sed ullamcorper lectus massa, a vehicula augue sollicitudin in. Fusce eu pellentesque turpis. Phasellus ultricies dapibus libero in sollicitudin. Mauris maximus odio nec tortor tempus iaculis. Nulla tempus, elit nec luctus sagittis, mauris quam semper arcu, non auctor mauris eros non erat. Donec lorem leo, fringilla eget ante eget, commodo faucibus orci. Ut aliquam imperdiet nisl, eu condimentum magna.

  Suspendisse facilisis nunc enim, sit amet efficitur lorem consequat a. Pellentesque ullamcorper fringilla turpis, quis rutrum tellus porttitor sit amet. Donec sed suscipit augue, vitae porttitor massa. Cras euismod nulla at enim vulputate, elementum pretium augue suscipit. Etiam sollicitudin arcu neque, id malesuada velit dictum ut. In facilisis euismod egestas. Mauris vulputate urna sed massa vestibulum, eget pellentesque ipsum mollis. Mauris scelerisque ante non accumsan commodo. Nullam condimentum massa eu enim sodales, vel tincidunt orci convallis. Aliquam erat volutpat. Maecenas aliquam et nibh mollis elementum. Suspendisse facilisis laoreet massa, eget iaculis quam aliquam eget. Aliquam eu massa ac risus sodales viverra. Mauris consequat libero nibh, sit amet maximus ipsum porttitor non. Morbi eleifend arcu vulputate ligula sagittis congue. Nullam laoreet augue vitae mollis lobortis.

  Curabitur nulla est, fermentum sed nunc a, pretium imperdiet ipsum. Pellentesque varius lectus metus, non laoreet erat imperdiet blandit. Suspendisse dapibus, mauris non luctus accumsan, dolor nisl laoreet erat, sit amet tempus eros erat a quam. Nullam justo turpis, iaculis vitae libero in, mattis maximus nisl. Proin venenatis leo ut orci interdum, ac condimentum arcu vestibulum. Cras placerat magna eu urna accumsan tincidunt. Cras massa dui, aliquam ut enim et, malesuada cursus ex.

  Integer convallis placerat nibh quis vestibulum. Etiam venenatis dignissim eleifend. Praesent ex libero, malesuada in lectus et, dignissim sagittis felis. Vivamus vulputate vel nibh ac pharetra. Sed ac maximus ex, non tempus metus. In vel metus vehicula, tempus orci sed, pharetra ipsum. Nulla imperdiet consequat faucibus.

  In risus libero, mollis sit amet nisi et, consequat vestibulum risus. Vestibulum dui libero, ultrices in bibendum eget, cursus sed leo. Integer justo justo, scelerisque ut elit ac, aliquet scelerisque ipsum. Pellentesque in blandit massa. Curabitur et sem a nulla accumsan vulputate. Nunc finibus aliquet tellus ac fringilla. Nulla venenatis magna at dui hendrerit suscipit. Pellentesque venenatis quis ante id mollis. Donec viverra erat vitae pharetra posuere. Praesent sed bibendum ligula, nec accumsan justo. Suspendisse quis libero at risus molestie ultricies. Vestibulum pellentesque odio suscipit velit commodo, a luctus nisi mattis. Donec ultricies pellentesque ante, ac elementum nibh imperdiet eget. Nam at tellus tincidunt, pulvinar ligula ac, egestas ex. Quisque urna lacus, efficitur tristique interdum non, porta vel neque. Maecenas neque nibh, facilisis a fermentum ut, tempus a lacus.

  Morbi felis eros, placerat in dictum non, consectetur eget enim. Aliquam sodales faucibus dolor, sed finibus neque bibendum vel. Proin laoreet commodo finibus. Morbi a interdum metus. Fusce sodales egestas urna aliquet egestas. Vestibulum pretium purus pellentesque odio interdum iaculis. Vivamus ut placerat leo. Aenean condimentum elementum rhoncus. Ut id consequat ex. Praesent tincidunt hendrerit eleifend.

  Mauris at risus vestibulum nunc maximus commodo eget lobortis nisl. Morbi sagittis sed sapien id accumsan. Nulla euismod venenatis ante eget dignissim. Etiam a urna eget enim bibendum egestas. Proin id mattis lacus, ac pellentesque orci. Morbi enim lectus, ultrices ut dui ut, mattis sodales ex. Donec euismod, est sit amet rhoncus luctus, nisi nisi egestas leo, sed ultrices arcu odio et quam. In hac habitasse platea dictumst. Aenean suscipit scelerisque erat, eu eleifend risus. Donec ornare maximus ligula vitae pellentesque. Nulla facilisi. Vestibulum vulputate odio sed ex consequat, in egestas odio rutrum. Cras suscipit dignissim est, placerat posuere enim interdum ut. Fusce molestie nulla ut consequat cursus. Maecenas tempus molestie egestas.

  Maecenas semper efficitur mi, vitae eleifend elit. Donec maximus elementum commodo. Aenean eget venenatis nisl, lobortis pretium leo. In ut libero nec neque vulputate auctor quis nec massa. In hac habitasse platea dictumst. Vestibulum at lorem imperdiet, commodo ante a, elementum dui. Sed nunc augue, rutrum sit amet interdum sed, sollicitudin scelerisque magna.

  Sed vulputate laoreet nunc, ac lacinia felis ornare aliquam. Nullam massa ligula, faucibus tempus tempor tincidunt, euismod luctus lacus. Mauris dolor sapien, aliquam ut imperdiet in, vestibulum in nunc. Aenean ornare nisl scelerisque enim placerat hendrerit. Pellentesque sed purus suscipit, cursus risus vitae, rhoncus nisl. Curabitur eleifend et lectus vitae consectetur. Vivamus quis posuere est. 827 words"

content5 = "Duis consequat tincidunt iaculis. Phasellus tristique commodo nulla vel posuere. Curabitur tempor mauris vitae metus vehicula, at convallis leo rutrum. Cras pellentesque quam id felis pulvinar pellentesque. Maecenas ac quam sit amet libero tempor vehicula ac nec justo. Maecenas lacinia arcu eget eros congue dignissim. Fusce in enim vel purus feugiat molestie. Integer quis semper lacus. In at felis tristique est efficitur tempus ac efficitur ipsum. Maecenas viverra fermentum tempor. Vestibulum sed mi erat.

  Aliquam sit amet euismod ligula. Duis sodales sapien nisi, vel iaculis nibh porta eget. Vestibulum metus ligula, ornare molestie hendrerit sed, elementum vitae nibh. Aenean tristique vel sapien luctus vulputate. Donec et molestie purus. Sed finibus tincidunt purus nec sollicitudin. Etiam consectetur ac dolor vitae posuere. Donec ac eleifend massa. Duis imperdiet porta neque, eget venenatis nibh gravida sit amet. Pellentesque sagittis vestibulum velit, nec maximus libero pharetra ut. Sed iaculis tristique nunc at suscipit.

  Duis a lobortis nisl. Ut urna justo, aliquet at iaculis vitae, vehicula eu tellus. Sed bibendum faucibus mauris, et maximus justo vehicula sed. Vestibulum fermentum aliquet eros ac tristique. Aenean laoreet mauris ut felis blandit lacinia. Maecenas ultricies lorem nec tellus pulvinar sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed et dui id ex mollis sollicitudin. Suspendisse tempus neque ante, nec finibus nibh scelerisque eu.

  Suspendisse vehicula tellus ut nisi tempor, eu semper urna rhoncus. Pellentesque facilisis risus metus, sed fringilla tortor venenatis quis. Proin in luctus mauris. Maecenas eget convallis lorem, at scelerisque nibh. Vestibulum malesuada sapien mauris, ut aliquam leo cursus non. Donec pellentesque blandit volutpat. Duis faucibus vestibulum porttitor.

  Fusce sollicitudin tempus massa non viverra. Phasellus lobortis mi ut neque egestas, non ullamcorper ex vestibulum. Duis porttitor erat quis leo malesuada varius. Proin malesuada augue est, sollicitudin facilisis ipsum faucibus dapibus. Cras eleifend, neque id placerat maximus, libero erat porttitor leo, ac tincidunt sem tortor non nulla. Nulla id pellentesque est. In tincidunt felis augue. Donec ornare feugiat congue. Morbi tincidunt rhoncus sapien non sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce quis sapien semper, fermentum dui ac, dignissim justo. Interdum et malesuada fames ac ante ipsum primis in faucibus.

  Fusce id massa nec nunc euismod auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin ut urna placerat, cursus libero sed, malesuada quam. Cras mattis dignissim semper. Donec et diam non eros tempor tempor nec a ex. Mauris volutpat nunc quis facilisis volutpat. Vivamus bibendum felis ut pulvinar ornare. Maecenas hendrerit eros in urna porttitor, id hendrerit augue varius. Pellentesque finibus sagittis dolor vitae interdum. Etiam mollis aliquam mauris quis efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean eu diam nibh. Quisque faucibus erat ut tellus porttitor consequat. Nulla facilisi.

  Sed feugiat gravida tristique. Integer eu felis nec mi euismod commodo. Cras tincidunt arcu gravida, fringilla justo eu, facilisis eros. Aenean vitae dignissim lectus, id iaculis elit. Maecenas mollis aliquam sapien nec finibus. Praesent sed maximus arcu. Fusce urna nulla, vehicula at neque eu, hendrerit rutrum odio. In in tortor luctus, feugiat sapien eget, sodales orci. Donec interdum commodo sapien, eget vulputate mi molestie vitae. Integer magna enim, tristique at metus eu, accumsan fermentum ante. Suspendisse tristique lacus quis orci ultrices, et faucibus risus tristique.

  Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis auctor tincidunt tellus, luctus lacinia elit interdum ac. Proin ultrices nisi ac ante consequat, ut tincidunt nibh consequat. Aliquam erat volutpat. Phasellus nec lorem vitae diam tempus pretium at eu diam. Praesent feugiat sagittis sem, sed ornare urna sagittis sed. Donec euismod leo enim, id gravida nisl rhoncus eu. Donec quam nisl, auctor sit amet tortor vitae, blandit vestibulum elit. In sapien felis, interdum non ipsum quis, tincidunt mollis metus. Curabitur lacinia quam non semper tempor. Fusce malesuada diam eget dolor dapibus, ut imperdiet augue feugiat.

  Integer at facilisis lacus. Aenean ornare viverra sem at dictum. Curabitur et lacinia eros. Fusce laoreet, libero ultrices ornare fermentum, leo erat maximus neque, sit amet interdum quam odio ut est. Quisque ut massa a sem convallis interdum. Integer ex sem, dapibus malesuada sagittis eget, auctor in risus. Etiam dui risus, dignissim vel mattis vitae, vestibulum non eros. Duis ultricies libero elit, et faucibus diam rhoncus vel. Nam vel aliquet libero.

  Nunc tincidunt massa enim, sed rhoncus tellus mollis sit amet. Praesent non consequat ante. Ut varius leo ut pulvinar elementum. Aliquam viverra ornare orci, sed dictum justo consectetur a. Morbi id iaculis justo, at mattis enim. Nulla facilisi. Suspendisse diam massa, mollis in sagittis sit amet, laoreet sit amet sem. Donec ullamcorper finibus odio, at semper purus pharetra porta. Donec ultricies, turpis eget tincidunt tempor, quam ligula dapibus libero, at sodales lectus mi ac lacus. Donec in condimentum sapien. Aenean pellentesque sem sit amet tellus tempor pellentesque. Proin ultrices accumsan odio vel consequat. 818 words"

post1 = Post.create(title: "title",   subtitle: "subtitle",   content: content1,   image: "image.jpg")
post2 = Post.create(title: "title2",  subtitle: "subtitle2",  content: content2,  image: "image2.jpg")
post3 = Post.create(title: "title3",  subtitle: "subtitle3",  content: content3,  image: "image3.jpg")
post4 = Post.create(title: "title4",  subtitle: "subtitle4",  content: content4,  image: "image4.jpg")
post5 = Post.create(title: "title5",  subtitle: "subtitle5",  content: content5,  image: "image5.jpg")

puts "seeded #{Post.count} posts!"



Comment.delete_all
print "Seeding database with comments..."

comment01 = Comment.create(title: "comment01", user_comment: "Lorem", post: post1)
comment02 = Comment.create(title: "comment02", user_comment: "Ipsum", post: post1)
comment03 = Comment.create(title: "comment03", user_comment: "Potato", post: post1)

comment04 = Comment.create(title: "comment04", user_comment: "Tomato", post: post2)
comment05 = Comment.create(title: "comment05", user_comment: "Uncle", post: post2)
comment06 = Comment.create(title: "comment06", user_comment: "Aunt", post: post2)

comment07 = Comment.create(title: "comment07", user_comment: "Bat", post: post3)
comment08 = Comment.create(title: "comment08", user_comment: "Cat", post: post3)
comment09 = Comment.create(title: "comment09", user_comment: "Charles", post: post3)

comment10 = Comment.create(title: "comment10", user_comment: "Barrels", post: post4)
comment11 = Comment.create(title: "comment11", user_comment: "Wow", post: post4)
comment12 = Comment.create(title: "comment12", user_comment: "This is a comment", post: post4)

comment13 = Comment.create(title: "comment13", user_comment: "Outstanding", post: post5)
comment14 = Comment.create(title: "comment14", user_comment: "Demanding", post: post5)
comment15 = Comment.create(title: "comment15", user_comment: "Borem", post: post5)

puts "seeded #{Comment.count} comments!"
